dist: xenial
language: python
services:
    - docker
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "nightly"
env:
    - TOX_VERSION="tox-2.x"
    - TOX_VERSION="tox-3.x"
install:
    - pip install --constraint "$TOX_VERSION" .
script: "tox"
